services:
  ocelot:
    build:
      context: .
      dockerfile: API_Gateway_Demo/Dockerfile
      
    container_name: ocelot-gateway
    ports:
      - "5222:8080"
    extra_hosts:
      host.docker.internal: host-gateway